{{- if .Values.service.enabled }}
{{- include "socair.validate" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "socair.fullname" . }}
  labels:
    {{- include "socair.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "socair.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
