// Command fpgen writes a license body fingerprint for the catalogue:
//
//	go run ./internal/checks/license/fpgen -id mit -source <url> mit.txt \
//	  > internal/checks/license/bodies/mit.txt
//
// The input is the license's canonical text, with [[ and ]] around a part a
// copy may leave out whole (an appendix) and {{ and }} around a placeholder a
// copy fills in (a holder's name); see license.Fingerprint. The output holds
// shingle hashes, not the text, so the repository carries no license text.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"

	"github.com/defilantech/socair/internal/checks/license"
)

func main() {
	id := flag.String("id", "", "catalogue id the fingerprint identifies")
	source := flag.String("source", "", "where the canonical text came from")
	flag.Parse()
	if *id == "" || *source == "" || flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: fpgen -id <id> -source <url> <canonical text>")
		os.Exit(2)
	}
	text, err := os.ReadFile(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	shingles, err := license.Fingerprint(string(text))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	count := map[byte]int{}
	for _, s := range shingles {
		count[s.Kind]++
	}
	w := bufio.NewWriter(os.Stdout)
	fmt.Fprintf(w, "# %s: body fingerprint, %d shingles in text order: %d required (r), %d omittable (o), %d placeholder (p).\n",
		*id, len(shingles), count[license.Required], count[license.Omittable], count[license.Placeholder])
	fmt.Fprintf(w, "# Generated by internal/checks/license/fpgen from %s.\n", *source)
	for _, s := range shingles {
		fmt.Fprintf(w, "%c %016x\n", s.Kind, s.Hash)
	}
	if err := w.Flush(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
